DROP DATABASE IF EXISTS work;
CREATE DATABASE work;
ALTER DATABASE work SET timezone TO 'Europe/Moscow';

\c work;

CREATE EXTENSION pg_trgm;

DROP USER IF EXISTS work;
CREATE USER work WITH PASSWORD 'work';
DROP SCHEMA IF EXISTS work;
CREATE SCHEMA AUTHORIZATION work;